# This is the config for simple pqopen app
[powersystem]
nominal_frequency = 50.0
zcd_channel = "U1"

[powersystem.phase.1]
u_channel = "U1"
i_channel = "I1"

[powersystem.phase.2]
u_channel = "U2"
i_channel = "I2"

[powersystem.phase.3]
u_channel = "U3"
i_channel = "I3"

[storageplan.csv_1s]
endpoint = "csv"
channels = []
interval_sec = 1

[storageplan.daqopenserver_10s]
endpoint = "daqopen-server"
channels = []
interval_sec = 10

[endpoint.csv]
file_path = "/tmp/"

[endpoint.daqopen-server]
hostname = "localhost"

[zmq_server]
port=50001
host="pqopen-0011"